// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApHg94Pn2vmC1sUhYRLJvT6vRvUFvHz4M',
    appId: '1:257429087396:web:a693a1de078e2241263231',
    messagingSenderId: '257429087396',
    projectId: 'cliqueconnect-eb893',
    authDomain: 'cliqueconnect-eb893.firebaseapp.com',
    storageBucket: 'cliqueconnect-eb893.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZyG37MiihBDwndVpRJxAXqTdCLVkpn6I',
    appId: '1:257429087396:android:de9fdcb8400fa449263231',
    messagingSenderId: '257429087396',
    projectId: 'cliqueconnect-eb893',
    storageBucket: 'cliqueconnect-eb893.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ2E7dWYeAA8N5A7cB0-04902oG8Rdhnk',
    appId: '1:257429087396:ios:8a1ead7adf9a6776263231',
    messagingSenderId: '257429087396',
    projectId: 'cliqueconnect-eb893',
    storageBucket: 'cliqueconnect-eb893.appspot.com',
    iosBundleId: 'cliqueconnect.com.testCliqueConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJ2E7dWYeAA8N5A7cB0-04902oG8Rdhnk',
    appId: '1:257429087396:ios:d17f4896e1ae0e29263231',
    messagingSenderId: '257429087396',
    projectId: 'cliqueconnect-eb893',
    storageBucket: 'cliqueconnect-eb893.appspot.com',
    iosBundleId: 'cliqueconnect.com.testCliqueConnect.RunnerTests',
  );
}
